name: Update AED

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixpkgs-23.11-darwin
          extra_nix_config: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.nixos.org/

      - name: Install dependencies
        run: |
          nix-shell --pure --run true

      - name: Setup cache
        uses: actions/cache@v4
        id: cache
        with:
          key: cache
          path: /cache

      - name: Restore .osm_cache.json
        if: steps.cache.outputs.cache-hit == 'true'
        run: |
          cp /cache/.osm_cache.json .

      - name: Update AED
        run: |
          nix-shell --pure --run "python main.py"

      - name: Save .osm_cache.json
        run: |
          cp .osm_cache.json /cache

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Update AED"
          git push
