name: Update AED

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Extract nixpkgs hash
        run: |
          nixpkgs_hash=$(grep -o -P '(?<=archive/)[0-9a-f]{40}(?=\.tar\.gz)' shell.nix)
          echo "NIXPKGS_HASH=$nixpkgs_hash" >> $GITHUB_ENV

      - name: Cache Nix store
        uses: actions/cache@v4
        id: nix-cache
        with:
          key: nix-${{ runner.os }}-${{ env.NIXPKGS_HASH }}
          path: /tmp/nix-cache

      - name: Import Nix store cache
        if: steps.nix-cache.outputs.cache-hit == 'true'
        run: |
          nix-store --import < /tmp/nix-cache

      - name: Cache Python venv
        uses: actions/cache@v4
        with:
          key: python-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
          path: |
            ~/.cache/pypoetry
            .venv

      - name: Install dependencies
        run: |
          nix-shell --pure --run true

      - name: Cache OSM data
        uses: actions/cache@v4
        id: osm-cache
        with:
          key: cache
          path: /tmp/osm-cache

      - name: Import .osm_cache.json
        if: steps.osm-cache.outputs.cache-hit == 'true'
        run: |
          cp /tmp/osm-cache/.osm_cache.json .

      - name: Update AED
        run: |
          nix-shell --pure --run "python main.py"

      - name: Export .osm_cache.json
        run: |
          mkdir -p /tmp/osm-cache
          cp .osm_cache.json /tmp/osm-cache

      - name: Export Nix store cache
        if: steps.nix-cache.outputs.cache-hit != 'true'
        run: |
          nix-store --export $(find /nix/store -maxdepth 1 -name '*-*') > /tmp/nix-cache

      - name: Commit changes
        run: |
          status=$(cat status.txt)
          git config user.name github-actions
          git config user.email github-actions@github.com
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -am "Update AED ($status)"
            git push
          fi
